export const FIELD_DEFINITIONS = [
  {
    key: "periodMonth",
    label: "月份",
    type: "month",
    required: true,
    synonyms: ["月份", "期间", "年月", "month", "period", "period_month", "日期"],
  },
  {
    key: "salesRevenue",
    label: "销售收入",
    type: "money",
    required: true,
    synonyms: ["销售收入", "销售额", "营业收入", "收入", "销售", "sales", "revenue", "sales_revenue"],
  },
  {
    key: "productCost",
    label: "商品成本",
    type: "money",
    required: false,
    synonyms: ["商品成本", "成本", "主营业务成本", "货品成本", "采购成本", "product_cost", "cost"],
  },
  {
    key: "uploadedGrossProfit",
    label: "毛利",
    type: "money",
    required: false,
    synonyms: ["毛利", "gross_profit", "gross profit"],
  },
  {
    key: "platformFee",
    label: "平台扣点",
    type: "money",
    required: false,
    synonyms: ["平台扣点", "平台服务费", "平台费", "佣金", "平台佣金", "platform_fee"],
  },
  {
    key: "adCost",
    label: "推广费用",
    type: "money",
    required: false,
    synonyms: ["推广费用", "广告费", "投放费用", "营销费用", "广告费用", "ad_cost", "marketing"],
  },
  {
    key: "refundAmount",
    label: "退款金额",
    type: "money",
    required: false,
    synonyms: ["退款金额", "退货退款", "退款", "退款额", "refund", "refund_amount"],
  },
  {
    key: "afterSalesCost",
    label: "售后费用",
    type: "money",
    required: false,
    synonyms: ["售后费用", "售后成本", "售后", "after_sales_cost"],
  },
  {
    key: "logisticsCost",
    label: "物流费用",
    type: "money",
    required: false,
    synonyms: ["物流费用", "快递费", "运费", "配送费", "logistics_cost"],
  },
  {
    key: "warehouseCost",
    label: "仓储费用",
    type: "money",
    required: false,
    synonyms: ["仓储费用", "仓储费", "仓库费用", "warehouse_cost"],
  },
  {
    key: "laborCost",
    label: "人工费用",
    type: "money",
    required: false,
    synonyms: ["人工费用", "人员成本", "人力成本", "工资", "薪酬", "labor_cost"],
  },
  {
    key: "managementCost",
    label: "管理费用",
    type: "money",
    required: false,
    synonyms: ["管理费用", "办公费用", "行政费用", "management_cost"],
  },
  {
    key: "otherCost",
    label: "其他费用",
    type: "money",
    required: false,
    synonyms: ["其他费用", "其他支出", "其他", "other_cost"],
  },
];

export const EDITABLE_FIELDS = FIELD_DEFINITIONS.filter((field) => {
  return field.key !== "uploadedGrossProfit";
});

export const MONEY_INPUT_KEYS = [
  "salesRevenue",
  "productCost",
  "platformFee",
  "adCost",
  "refundAmount",
  "afterSalesCost",
  "logisticsCost",
  "warehouseCost",
  "laborCost",
  "managementCost",
  "otherCost",
];

export const METRIC_META = {
  salesRevenue: { label: "销售收入", unit: "money", formula: "销售收入 = 用户录入或上传字段" },
  productCost: { label: "商品成本", unit: "money", formula: "商品成本 = 用户录入或上传字段" },
  grossProfit: { label: "毛利", unit: "money", formula: "毛利 = 销售收入 - 商品成本" },
  grossMargin: { label: "毛利率", unit: "rate", formula: "毛利率 = 毛利 / 销售收入" },
  platformFee: { label: "平台扣点", unit: "money", formula: "平台扣点 = 用户录入或上传字段" },
  platformFeeRate: { label: "平台扣点率", unit: "rate", formula: "平台扣点率 = 平台扣点 / 销售收入" },
  adCost: { label: "推广费用", unit: "money", formula: "推广费用 = 用户录入或上传字段" },
  adCostRate: { label: "推广费率", unit: "rate", formula: "推广费率 = 推广费用 / 销售收入" },
  refundAmount: { label: "退款金额", unit: "money", formula: "退款金额 = 用户录入或上传字段" },
  refundRate: { label: "退款率", unit: "rate", formula: "退款率 = 退款金额 / 销售收入" },
  afterSalesCost: { label: "售后费用", unit: "money", formula: "售后费用 = 用户录入或上传字段" },
  afterSalesCostRate: { label: "售后费用率", unit: "rate", formula: "售后费用率 = 售后费用 / 销售收入" },
  logisticsCost: { label: "物流费用", unit: "money", formula: "物流费用 = 用户录入或上传字段" },
  logisticsCostRate: { label: "物流费用率", unit: "rate", formula: "物流费用率 = 物流费用 / 销售收入" },
  warehouseCost: { label: "仓储费用", unit: "money", formula: "仓储费用 = 用户录入或上传字段" },
  warehouseCostRate: { label: "仓储费用率", unit: "rate", formula: "仓储费用率 = 仓储费用 / 销售收入" },
  laborCost: { label: "人工费用", unit: "money", formula: "人工费用 = 用户录入或上传字段" },
  laborCostRate: { label: "人工费用率", unit: "rate", formula: "人工费用率 = 人工费用 / 销售收入" },
  managementCost: { label: "管理费用", unit: "money", formula: "管理费用 = 用户录入或上传字段" },
  managementCostRate: { label: "管理费用率", unit: "rate", formula: "管理费用率 = 管理费用 / 销售收入" },
  otherCost: { label: "其他费用", unit: "money", formula: "其他费用 = 用户录入或上传字段" },
  totalExpense: { label: "总费用", unit: "money", formula: "总费用 = 平台扣点 + 推广费用 + 退款金额 + 售后费用 + 物流费用 + 仓储费用 + 人工费用 + 管理费用 + 其他费用" },
  netProfit: { label: "净利润", unit: "money", formula: "净利润 = 销售收入 - 商品成本 - 总费用" },
  netMargin: { label: "净利率", unit: "rate", formula: "净利率 = 净利润 / 销售收入" },
};

export const FOCUS_METRICS = [
  "salesRevenue",
  "grossMargin",
  "adCostRate",
  "platformFeeRate",
  "refundRate",
  "laborCostRate",
  "managementCostRate",
  "totalExpense",
  "netProfit",
  "netMargin",
];

export const RATE_METRICS = [
  "grossMargin",
  "netMargin",
  "adCostRate",
  "platformFeeRate",
  "refundRate",
  "afterSalesCostRate",
  "logisticsCostRate",
  "warehouseCostRate",
  "laborCostRate",
  "managementCostRate",
];

export const TARGET_FIELDS = {
  grossMargin: "targetGrossMargin",
  netMargin: "targetNetMargin",
  adCostRate: "targetAdCostRate",
  refundRate: "targetRefundRate",
  laborCostRate: "targetLaborCostRate",
  managementCostRate: "targetManagementCostRate",
};

export const BENCHMARK_FIELDS = {
  grossMargin: "grossMargin",
  netMargin: "netMargin",
  adCostRate: "adCostRate",
  refundRate: "refundRate",
  laborCostRate: "laborCostRate",
  managementCostRate: "managementCostRate",
};

export const LOWER_IS_BETTER = new Set([
  "adCostRate",
  "platformFeeRate",
  "refundRate",
  "afterSalesCostRate",
  "logisticsCostRate",
  "warehouseCostRate",
  "laborCostRate",
  "managementCostRate",
  "totalExpense",
]);

export const DEFAULT_TARGETS = {
  year: 2026,
  annualSalesTarget: 9600000,
  annualNetProfitTarget: 1080000,
  targetGrossMargin: 0.32,
  targetNetMargin: 0.12,
  targetAdCostRate: 0.12,
  targetRefundRate: 0.04,
  targetLaborCostRate: 0.08,
  targetManagementCostRate: 0.045,
};

export const DEFAULT_BENCHMARK = {
  id: "benchmark-healthy-profit",
  benchmarkName: "优秀同行标杆",
  benchmarkType: "优秀同行",
  grossMargin: 0.36,
  netMargin: 0.14,
  adCostRate: 0.1,
  refundRate: 0.035,
  laborCostRate: 0.07,
  managementCostRate: 0.04,
};

export const SEED_RECORDS = [
  {
    id: "seed-2026-01",
    periodMonth: "2026-01",
    salesRevenue: 620000,
    productCost: 425000,
    platformFee: 39000,
    adCost: 64000,
    refundAmount: 26000,
    afterSalesCost: 8000,
    logisticsCost: 24000,
    warehouseCost: 11000,
    laborCost: 47000,
    managementCost: 28000,
    otherCost: 9000,
  },
  {
    id: "seed-2026-02",
    periodMonth: "2026-02",
    salesRevenue: 710000,
    productCost: 475000,
    platformFee: 44500,
    adCost: 76000,
    refundAmount: 31000,
    afterSalesCost: 9400,
    logisticsCost: 27000,
    warehouseCost: 12000,
    laborCost: 50000,
    managementCost: 30000,
    otherCost: 10000,
  },
  {
    id: "seed-2026-03",
    periodMonth: "2026-03",
    salesRevenue: 760000,
    productCost: 498000,
    platformFee: 48000,
    adCost: 85000,
    refundAmount: 33000,
    afterSalesCost: 10500,
    logisticsCost: 28500,
    warehouseCost: 13000,
    laborCost: 53500,
    managementCost: 31000,
    otherCost: 9500,
  },
  {
    id: "seed-2026-04",
    periodMonth: "2026-04",
    salesRevenue: 820000,
    productCost: 535000,
    platformFee: 52000,
    adCost: 93000,
    refundAmount: 36500,
    afterSalesCost: 11800,
    logisticsCost: 31000,
    warehouseCost: 14200,
    laborCost: 56200,
    managementCost: 33500,
    otherCost: 11500,
  },
  {
    id: "seed-2026-05",
    periodMonth: "2026-05",
    salesRevenue: 880000,
    productCost: 573000,
    platformFee: 56000,
    adCost: 101000,
    refundAmount: 38000,
    afterSalesCost: 12600,
    logisticsCost: 33000,
    warehouseCost: 15500,
    laborCost: 58500,
    managementCost: 34500,
    otherCost: 13000,
  },
  {
    id: "seed-2026-06",
    periodMonth: "2026-06",
    salesRevenue: 955000,
    productCost: 642000,
    platformFee: 61500,
    adCost: 149000,
    refundAmount: 52000,
    afterSalesCost: 15800,
    logisticsCost: 37800,
    warehouseCost: 16500,
    laborCost: 69500,
    managementCost: 41000,
    otherCost: 14500,
  },
];

export const DEFAULT_RULES = [
  {
    id: "ad-rate-mom",
    ruleName: "推广费率环比异常",
    ruleDescription: "用于判断推广费用是否异常上升",
    metricKey: "adCostRate",
    compareType: "mom-point-increase",
    defaultYellowThreshold: 0.03,
    defaultRedThreshold: 0.05,
    currentYellowThreshold: 0.03,
    currentRedThreshold: 0.05,
    isEnabled: true,
    suggestionText: "建议排查各渠道 ROI、低投产计划、投放预算变化，以及是否存在为了冲销售额牺牲利润的情况。",
    defaultSuggestionText: "建议排查各渠道 ROI、低投产计划、投放预算变化，以及是否存在为了冲销售额牺牲利润的情况。",
    isSystemRule: true,
  },
  {
    id: "gross-margin-target",
    ruleName: "毛利率低于目标",
    ruleDescription: "用于判断毛利率是否偏离经营目标",
    metricKey: "grossMargin",
    compareType: "target-gap-lower",
    defaultYellowThreshold: 0.02,
    defaultRedThreshold: 0.05,
    currentYellowThreshold: 0.02,
    currentRedThreshold: 0.05,
    isEnabled: true,
    suggestionText: "建议排查采购成本、促销折扣、低毛利产品成交占比、价格体系和供应链成本。",
    defaultSuggestionText: "建议排查采购成本、促销折扣、低毛利产品成交占比、价格体系和供应链成本。",
    isSystemRule: true,
  },
  {
    id: "net-margin-target",
    ruleName: "净利率低于目标",
    ruleDescription: "用于判断净利率是否低于目标水平",
    metricKey: "netMargin",
    compareType: "target-gap-lower",
    defaultYellowThreshold: 0.02,
    defaultRedThreshold: 0.04,
    currentYellowThreshold: 0.02,
    currentRedThreshold: 0.04,
    isEnabled: true,
    suggestionText: "建议综合排查毛利率、推广费率、人工费用率、退款率和管理费用率。",
    defaultSuggestionText: "建议综合排查毛利率、推广费率、人工费用率、退款率和管理费用率。",
    isSystemRule: true,
  },
  {
    id: "revenue-up-profit-down",
    ruleName: "收入增长但净利润下降",
    ruleDescription: "用于识别增收不增利",
    metricKey: "netProfit",
    compareType: "revenue-up-profit-down",
    defaultYellowThreshold: 0,
    defaultRedThreshold: 0,
    currentYellowThreshold: 0,
    currentRedThreshold: 0,
    isEnabled: true,
    suggestionText: "本月出现增收不增利，说明增长质量较差，建议优先排查毛利结构和费用率。",
    defaultSuggestionText: "本月出现增收不增利，说明增长质量较差，建议优先排查毛利结构和费用率。",
    isSystemRule: true,
    redOnly: true,
  },
  {
    id: "annual-profit-progress",
    ruleName: "年度利润进度落后",
    ruleDescription: "用于判断年度利润目标完成率是否低于时间进度",
    metricKey: "netProfit",
    compareType: "annual-progress-gap",
    defaultYellowThreshold: 0.05,
    defaultRedThreshold: 0.1,
    currentYellowThreshold: 0.05,
    currentRedThreshold: 0.1,
    isEnabled: true,
    suggestionText: "当前利润完成进度低于时间进度，若不调整，年底可能无法完成年度利润目标。",
    defaultSuggestionText: "当前利润完成进度低于时间进度，若不调整，年底可能无法完成年度利润目标。",
    isSystemRule: true,
  },
  {
    id: "refund-rate-mom",
    ruleName: "退款率异常上升",
    ruleDescription: "用于判断退款金额占收入比例是否异常上升",
    metricKey: "refundRate",
    compareType: "mom-point-increase",
    defaultYellowThreshold: 0.01,
    defaultRedThreshold: 0.03,
    currentYellowThreshold: 0.01,
    currentRedThreshold: 0.03,
    isEnabled: true,
    suggestionText: "建议排查产品质量、客服承诺、发货时效、页面描述和售后处理流程。",
    defaultSuggestionText: "建议排查产品质量、客服承诺、发货时效、页面描述和售后处理流程。",
    isSystemRule: true,
  },
  {
    id: "labor-rate-mom",
    ruleName: "人工费用率异常上升",
    ruleDescription: "用于判断人工费用率是否异常上升",
    metricKey: "laborCostRate",
    compareType: "mom-point-increase",
    defaultYellowThreshold: 0.02,
    defaultRedThreshold: 0.04,
    currentYellowThreshold: 0.02,
    currentRedThreshold: 0.04,
    isEnabled: true,
    suggestionText: "建议排查人员效率、团队产出、人均销售额和固定人工成本。",
    defaultSuggestionText: "建议排查人员效率、团队产出、人均销售额和固定人工成本。",
    isSystemRule: true,
  },
  {
    id: "management-rate-mom",
    ruleName: "管理费用率异常上升",
    ruleDescription: "用于判断管理费用率是否异常上升",
    metricKey: "managementCostRate",
    compareType: "mom-point-increase",
    defaultYellowThreshold: 0.02,
    defaultRedThreshold: 0.04,
    currentYellowThreshold: 0.02,
    currentRedThreshold: 0.04,
    isEnabled: true,
    suggestionText: "建议排查非业务必要支出、办公费用、管理成本和临时性支出。",
    defaultSuggestionText: "建议排查非业务必要支出、办公费用、管理成本和临时性支出。",
    isSystemRule: true,
  },
  {
    id: "negative-profit",
    ruleName: "净利润为负",
    ruleDescription: "用于识别当月亏损",
    metricKey: "netProfit",
    compareType: "negative-value",
    defaultYellowThreshold: 0,
    defaultRedThreshold: 0,
    currentYellowThreshold: 0,
    currentRedThreshold: 0,
    isEnabled: true,
    suggestionText: "本月出现亏损，需要优先排查收入规模、毛利率、推广费用、固定费用和退款售后成本。",
    defaultSuggestionText: "本月出现亏损，需要优先排查收入规模、毛利率、推广费用、固定费用和退款售后成本。",
    isSystemRule: true,
    redOnly: true,
  },
  {
    id: "expense-growth-faster",
    ruleName: "费用增长快于收入增长",
    ruleDescription: "用于判断费用扩张是否快于收入增长",
    metricKey: "totalExpense",
    compareType: "expense-growth-faster",
    defaultYellowThreshold: 0.05,
    defaultRedThreshold: 0.1,
    currentYellowThreshold: 0.05,
    currentRedThreshold: 0.1,
    isEnabled: true,
    suggestionText: "费用增长快于收入增长，说明经营杠杆变差，需要排查费用投入是否带来有效增长。",
    defaultSuggestionText: "费用增长快于收入增长，说明经营杠杆变差，需要排查费用投入是否带来有效增长。",
    isSystemRule: true,
  },
];
